{% set name = "cctk" %}
{% set version = "0.2.17" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 549cb9c97ec34b644e6afa3d808a7de84d1cabea57caa8472247aa2a9114a40f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"

requirements:
  host:
    - basis_set_exchange
    - importlib_resources
    - networkx
    - numpy
    - pip
    - pyahocorasick
    - python
    - pyyaml
    - scipy
  run:
    - basis_set_exchange
    - importlib_resources
    - networkx
    - numpy
    - pyahocorasick
    - python
    - pyyaml
    - scipy

test:
  imports:
    - cctk
    - cctk.data
    - cctk.groups

about:
  home: "https://github.com/ekwan/cctk"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "computational chemistry toolkit"
  doc_url: https://cctk.readthedocs.io/en/latest/ 
  dev_url: https://github.com/ekwan/cctk 

extra:
  recipe-maintainers:
    - corinwagen
