channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - tabulate
  - tqdm
  - pandas
  - matplotlib
  - numpy
  - xtb
  - rdkit
  - pip:
      - numpy
      - scipy
      - networkx
      - importlib_resources
      - sphinx_bootstrap_theme
      - pyahocorasick
      - basis_set_exchange
      - pyyaml
